# Generated by Django 6.0.5 on 2026-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
